services:
  activemq:
    image: apache/activemq-artemis
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
        - ARTEMIS_USER=artemis
        - ARTEMIS_PASSWORD=artemis
        - ANONYMOUS_LOGIN=false
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8161" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clientdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  service1:
    build: ./service1
    ports:
      - "8081:8081"
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      - SPRING_ARTEMIS_BROKER_URL=tcp://activemq:61616
      - SPRING_ARTEMIS_USER=artemis
      - SPRING_ARTEMIS_PASSWORD=artemis

  service2:
    build: ./service2
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      - SPRING_ARTEMIS_BROKER_URL=tcp://activemq:61616
      - SPRING_ARTEMIS_USER=artemis
      - SPRING_ARTEMIS_PASSWORD=artemis

  service3:
    build: ./service3
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      - SPRING_ARTEMIS_BROKER_URL=tcp://activemq:61616
      - SPRING_ARTEMIS_USER=artemis
      - SPRING_ARTEMIS_PASSWORD=artemis

  service4:
    build: ./service4
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      - SPRING_ARTEMIS_BROKER_URL=tcp://activemq:61616
      - SPRING_ARTEMIS_USER=artemis
      - SPRING_ARTEMIS_PASSWORD=artemis

  service5:
    build: ./service5
    depends_on:
      activemq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - SPRING_ARTEMIS_BROKER_URL=tcp://activemq:61616
      - SPRING_ARTEMIS_USER=artemis
      - SPRING_ARTEMIS_PASSWORD=artemis
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/clientdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8085:8085"

volumes:
  postgres-data: